#Override containers for dev
version: "2.4"
services:
  reverse_proxy:
    volumes:
      - .local/nginx:/data

  ui:
    command: yarn start
    mem_limit: 1g
    stdin_open: true
    build:
      args:
        - ANNUAIRE_ENV=dev
    environment:
      - FAST_REFRESH=false
    volumes:
      - ./ui:/app #Allows source folders to be watched

  server:
    command: ["yarn", "debug"]
    ports:
      - "127.0.0.1:9229:9229" #Allows remote debugging
    volumes:
      - ./server/src:/app/src #Allows source folders to be watched
      - .local/server:/data
      - .local/dne:/dne
    environment:
      - ANNUAIRE_ENV=dev
      - ANNUAIRE_LOG_LEVEL=debug

  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - .local/mongodb/db:/data/db
      - .local/mongodb/configdb:/data/configdb

