version: "2.4"
services:

  reverse_proxy:
    image: referentiel_reverse_proxy
    container_name: referentiel_reverse_proxy
    build:
      context: reverse_proxy
    mem_limit: 96m
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - referentiel_network
    depends_on:
      - server
      - ui

  ui:
    image: referentiel_ui
    container_name: referentiel_ui
    build:
      context: ui
    mem_limit: 96m
    networks:
      - referentiel_network
    depends_on:
      - server

  server:
    image: referentiel_server
    container_name: referentiel_server
    build:
      context: server
    mem_limit: 512m
    restart: unless-stopped
    networks:
      - referentiel_network
    depends_on:
      - mongodb
    environment:
      - REFERENTIEL_MONGODB_URI=mongodb://mongodb:27017/referentiel?retryWrites=true&w=majority

  mongodb:
    image: mongo:5.0.3-focal
    container_name: referentiel_mongodb
    command: --wiredTigerCacheSizeGB 3 --port 27017
    mem_limit: 3g
    restart: unless-stopped
    networks:
      - referentiel_network

networks:
  referentiel_network:
    name: referentiel_network
