#Override containers for dev
version: "2.4"
services:

  reverse_proxy:
    volumes:
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yaml
      - ./traefik/config:/etc/traefik/config
      - ./.local/certs:/certs

  ui:
    command: yarn start
    mem_limit: 2g
    stdin_open: true
    volumes:
      - ./ui:/app #Allows source folders to be watched
    environment:
      - FAST_REFRESH=false
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.tls=true"
      - "traefik.http.routers.ui.rule=Host(`localhost`) && PathPrefix(`/`)"

  server:
    command: [ "yarn", "debug" ]
    ports:
      - "127.0.0.1:9229:9229" #Allows remote debugging
    volumes:
      - ./server/src:/app/src #Allows source folders to be watched
      - .local/server:/data
    environment:
      - REFERENTIEL_ENV=dev
      - REFERENTIEL_LOG_LEVEL=debug
      - REFERENTIEL_LOG_DESTINATIONS=stdout,mongodb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.server.tls=true"

  mongodb:
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - .local/mongodb/db:/data/db
      - .local/mongodb/configdb:/data/configdb
