## STATIC CONFIG (restart traefik to update)
global:
  checkNewVersion: true

log:
  level: DEBUG

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    watch: true
  file:
    directory: /etc/traefik/config
    watch: true

entryPoints:
  websecure:
    address: :443
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
