name: Deploy
on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/run-playbook
        with:
          playbook: "deploy-app"
          envName: "recette"
          gitRevision: "develop"
          sshPrivateKey: "${{ secrets.SSH_PRIVATE_KEY }}"
          knownHosts: "${{ secrets.KNOWN_HOSTS }}"
